name: Generate Preview Site on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-preview:
    runs-on: pvtlcc-preview-arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: run kubectl
        run: |
          kubectl version
          ls -laR
